apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  namespace: test-manual-app
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
      }
    }