apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-gitops-automatic
  namespace: cluster-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/davecore82/openshift-cluster-gitops.git
    targetRevision: main
    path: test-gitops-automatic
  destination:
    server: https://kubernetes.default.svc
    namespace: test-gitops-automatic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true