# File: test-gitops-automatic/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: test-gitops-automatic
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP