apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator-subscription
  namespace: openshift-storage
  annotations:
    console.openshift.io/enable-plugins: ""
spec:
  channel: stable-4.18
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace